### ISSUE TITLE
Request: List targets in sequences according to LR

### ISSUE THREAD

**Issue by Eusti** [jarnoh/knobroom#16]
As I just switched controllers and even before trying to get the optimal mapping going I came across this quite often: The drop down menu in the mapping area almost follows the set up in LR...

In Lightroom the sequence (at least of the parameters that I think can be controlled):
White Balance
Temp
Tint
Exp2012
Contr2012
Highlights2012
Whites2012
Blacks2012
Clarity2012
Vibrance
Satuaration

etc.

I think it would be easier if the sequences would match each other...

Thx!

D.

**Comment by Eusti** [comment]
Now that I've played with it a bit I'm not too sure anymore if this is actually needed... For instance when setting up the Parametric Tone Curve your sequence makes a lot more sense to me than the LR one... I usually to the shadows first... Oh, well... ;)

D.

**Comment by jarnoh** [comment]
Fixed r681
