### ISSUE TITLE
Bug: r686: Plug-in Extras > Start Knobroom doesn't go to select midi controllers

### ISSUE THREAD

**Issue by Eusti** [jarnoh/knobroom#20]
I love the additional set up options in 686, unfortunately I can check them out as the plug in doesn't let me select my midi controller and doesn't let me connect... :(

Back to 679 for me! 

D.

**Comment by jarnoh** [comment]
Oops, there was a syntax error in the camera raw settings file, I've fixed it for r689 and added build-time validation for it as well.
